[package]
name = "lessanvil"
version = "1.0.0"
authors = ["icrayix"]
edition = "2021"
license = "MIT"
description = "Small CLI for reducing a Minecraft: Java Edition's world size by removing unused chunks."
repository = "https://github.com/icrayix/lessanvil"
readme = "README.md"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstream = "0.2.6"
clap = { version = "4.1.1", features = ["derive"] }
ctrlc = "3.4.0"
dialoguer = { version = "0.10.3", default-features = false }
env_logger = "0.10.0"
fastanvil = { version = "0.28.0", default-features = false }
fastnbt = "2.3.2"
indicatif = { version = "0.17.3", features = ["rayon"] }
log = "0.4.17"
owo-colors = "3.5.0"
rayon = "1.7.0"
serde = "1.0.159"
serde_json = "1.0.95"
thiserror = "1.0.40"
