[package]
name = "lessanvil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstream = "0.2.6"
anyhow = "1.0.70"
clap = { version = "4.1.1", features = ["derive"] }
env_logger = "0.10.0"
fastanvil = "0.27.0"
fastnbt = "2.3.2"
indicatif = { version = "0.17.3", features = ["rayon"] }
log = "0.4.17"
owo-colors = "3.5.0"
rayon = "1.7.0"
serde = "1.0.159"
